"""Consultant directory utilities for CureHelp+."""
from __future__ import annotations

from typing import Dict, List

HOSPITALS_DATA: List[Dict[str, str]] = [
    {
        "name": "Apollo Hospital",
        "address": "G-1, Block G, Sector 26, Noida, Uttar Pradesh 201301",
        "contact": "+91-120-255-9001",
        "speciality": "Multi-Speciality",
        "distance": "2.5 km",
        "location_url": "https://maps.google.com/?q=Apollo+Hospital+Sector+26+Noida",
        "website_url": "https://www.apollohospitals.com",
    },
    {
        "name": "Fortis Hospital",
        "address": "B-22, Sector 62, Noida, Uttar Pradesh 201301",
        "contact": "+91-120-240-2222",
        "speciality": "Multi-Speciality",
        "distance": "3.2 km",
        "location_url": "https://maps.google.com/?q=Fortis+Hospital+Sector+62+Noida",
        "website_url": "https://www.fortishealthcare.com",
    },
    {
        "name": "Max Super Speciality Hospital",
        "address": "W-3, Sector 1, Vaishali, Ghaziabad, Uttar Pradesh 201010",
        "contact": "+91-120-429-4444",
        "speciality": "Super Speciality",
        "distance": "4.1 km",
        "location_url": "https://maps.google.com/?q=Max+Super+Speciality+Hospital+Vaishali",
        "website_url": "https://www.maxhealthcare.in",
    },
    {
        "name": "Artemis Hospital",
        "address": "Sector 51, Gurugram, Haryana 122001",
        "contact": "+91-124-451-1111",
        "speciality": "Multi-Speciality",
        "distance": "5.8 km",
        "location_url": "https://maps.google.com/?q=Artemis+Hospital+Sector+51+Gurugram",
        "website_url": "https://www.artemishospitals.com",
    },
    {
        "name": "Medanta The Medicity",
        "address": "Sector 38, Gurugram, Haryana 122001",
        "contact": "+91-124-414-1414",
        "speciality": "Multi-Speciality",
        "distance": "6.5 km",
        "location_url": "https://maps.google.com/?q=Medanta+The+Medicity+Gurugram",
        "website_url": "https://www.medanta.org",
    },
    {
        "name": "AIIMS Delhi",
        "address": "Ansari Nagar, New Delhi, Delhi 110029",
        "contact": "+91-11-265-8858",
        "speciality": "Government Multi-Speciality",
        "distance": "7.2 km",
        "location_url": "https://maps.google.com/?q=AIIMS+Delhi+Ansari+Nagar",
        "website_url": "https://www.aiims.edu",
    },
    {
        "name": "Sir Ganga Ram Hospital",
        "address": "Sir Ganga Ram Hospital Marg, New Delhi 110060",
        "contact": "+91-11-257-3520",
        "speciality": "Multi-Speciality",
        "distance": "8.1 km",
        "location_url": "https://maps.google.com/?q=Sir+Ganga+Ram+Hospital+Delhi",
        "website_url": "https://www.sgrh.com",
    },
    {
        "name": "BLK-Max Super Speciality Hospital",
        "address": "Pusa Road, New Delhi 110005",
        "contact": "+91-11-3040-3040",
        "speciality": "Super Speciality",
        "distance": "8.7 km",
        "location_url": "https://maps.google.com/?q=BLK+Max+Hospital+Pusa+Road",
        "website_url": "https://www.blkmaxhospital.com",
    },
    {
        "name": "Indraprastha Apollo Hospital",
        "address": "Sarita Vihar, Delhi Mathura Road, New Delhi 110076",
        "contact": "+91-11-2692-5801",
        "speciality": "Multi-Speciality",
        "distance": "9.3 km",
        "location_url": "https://maps.google.com/?q=Indraprastha+Apollo+Hospital+Delhi",
        "website_url": "https://delhi.apollohospitals.com",
    },
    {
        "name": "Safdarjung Hospital",
        "address": "Ansari Nagar West, New Delhi 110029",
        "contact": "+91-11-2670-7444",
        "speciality": "Government Hospital",
        "distance": "10.2 km",
        "location_url": "https://maps.google.com/?q=Safdarjung+Hospital+Delhi",
        "website_url": "https://www.safdarjunghospital.org",
    },
    {
        "name": "RML Hospital",
        "address": "Baba Kharak Singh Marg, New Delhi 110001",
        "contact": "+91-11-2340-4238",
        "speciality": "Government Multi-Speciality",
        "distance": "11.5 km",
        "location_url": "https://maps.google.com/?q=RML+Hospital+Delhi",
        "website_url": "https://www.rmlh.nic.in",
    },
    {
        "name": "Dharamshila Narayana Hospital",
        "address": "Dharamshila Marg, Vasundhara Enclave, Delhi 110096",
        "contact": "+91-11-4306-6358",
        "speciality": "Oncology Speciality",
        "distance": "12.1 km",
        "location_url": "https://maps.google.com/?q=Dharamshila+Narayana+Hospital+Delhi",
        "website_url": "https://www.dnarayanahealth.org",
    },
    {
        "name": "Columbia Asia Hospital",
        "address": "Sector 25, Palam Vihar, Gurugram 122017",
        "contact": "+91-124-398-9896",
        "speciality": "Multi-Speciality",
        "distance": "13.2 km",
        "location_url": "https://maps.google.com/?q=Columbia+Asia+Hospital+Gurugram",
        "website_url": "https://www.columbiaindiahospitals.com",
    },
    {
        "name": "Felix Hospital",
        "address": "Sector 137, Noida, Uttar Pradesh 201305",
        "contact": "+91-120-711-7000",
        "speciality": "Multi-Speciality",
        "distance": "20.3 km",
        "location_url": "https://maps.google.com/?q=Felix+Hospital+Noida",
        "website_url": "https://www.felixhospital.com",
    },
]

DOCTORS_DATA: List[Dict[str, str]] = [
    {
        "name": "Dr. Rajesh Sharma",
        "contact": "+91-98765-43210",
        "address": "E-45, Sector 27, Noida, UP - 201301",
        "qualification": "MD, DM Cardiology",
        "specialization": "Cardiologist",
        "experience": "15 years",
        "rating": "4.8",
        "location_url": "https://maps.google.com/?q=E-45+Sector+27+Noida",
        "website_url": "https://www.drrajeshsharma-cardio.com",
    },
    {
        "name": "Dr. Priya Singh",
        "contact": "+91-98765-43211",
        "address": "F-12, Sector 18, Noida, UP - 201301",
        "qualification": "MBBS, MD Pediatrics",
        "specialization": "Pediatrician",
        "experience": "12 years",
        "rating": "4.7",
        "location_url": "https://maps.google.com/?q=F-12+Sector+18+Noida",
        "website_url": "https://www.drpriyasingh-pediatrics.com",
    },
    {
        "name": "Dr. Amit Kumar",
        "contact": "+91-98765-43212",
        "address": "B-25, Sector 34, Noida, UP - 201301",
        "qualification": "MBBS, MS Orthopedics",
        "specialization": "Orthopedic Surgeon",
        "experience": "18 years",
        "rating": "4.9",
        "location_url": "https://maps.google.com/?q=B-25+Sector+34+Noida",
        "website_url": "https://www.dramitkumar-ortho.com",
    },
    {
        "name": "Dr. Sunita Mehta",
        "contact": "+91-98765-43213",
        "address": "C-8, Sector 62, Noida, UP - 201301",
        "qualification": "MBBS, MD Gynecology",
        "specialization": "Gynecologist",
        "experience": "14 years",
        "rating": "4.8",
        "location_url": "https://maps.google.com/?q=C-8+Sector+62+Noida",
        "website_url": "https://www.drsunitamehta-gyno.com",
    },
    {
        "name": "Dr. Ravi Verma",
        "contact": "+91-98765-43214",
        "address": "D-14, Sector 15, Noida, UP - 201301",
        "qualification": "MBBS, MD Neurology",
        "specialization": "Neurologist",
        "experience": "16 years",
        "rating": "4.7",
        "location_url": "https://maps.google.com/?q=D-14+Sector+15+Noida",
        "website_url": "https://www.drraviverma-neuro.com",
    },
    {
        "name": "Dr. Anjali Gupta",
        "contact": "+91-98765-43215",
        "address": "G-7, Sector 29, Noida, UP - 201301",
        "qualification": "MBBS, MD Dermatology",
        "specialization": "Dermatologist",
        "experience": "10 years",
        "rating": "4.6",
        "location_url": "https://maps.google.com/?q=G-7+Sector+29+Noida",
        "website_url": "https://www.dranjaligupta-derma.com",
    },
    {
        "name": "Dr. Sanjay Malhotra",
        "contact": "+91-98765-43216",
        "address": "H-22, Sector 12, Noida, UP - 201301",
        "qualification": "MBBS, MS Ophthalmology",
        "specialization": "Ophthalmologist",
        "experience": "13 years",
        "rating": "4.8",
        "location_url": "https://maps.google.com/?q=H-22+Sector+12+Noida",
        "website_url": "https://www.drsanjaymalhotra-eye.com",
    },
    {
        "name": "Dr. Neha Joshi",
        "contact": "+91-98765-43217",
        "address": "A-5, Sector 33, Noida, UP - 201301",
        "qualification": "MBBS, MD Psychiatry",
        "specialization": "Psychiatrist",
        "experience": "11 years",
        "rating": "4.5",
        "location_url": "https://maps.google.com/?q=A-5+Sector+33+Noida",
        "website_url": "https://www.drnehajoshi-psych.com",
    },
    {
        "name": "Dr. Vikram Singh",
        "contact": "+91-98765-43218",
        "address": "F-18, Sector 20, Noida, UP - 201301",
        "qualification": "MBBS, MD General Medicine",
        "specialization": "General Physician",
        "experience": "20 years",
        "rating": "4.9",
        "location_url": "https://maps.google.com/?q=F-18+Sector+20+Noida",
        "website_url": "https://www.drvikramsingh-gp.com",
    },
    {
        "name": "Dr. Meera Patel",
        "contact": "+91-98765-43219",
        "address": "E-33, Sector 25, Noida, UP - 201301",
        "qualification": "MBBS, MS ENT",
        "specialization": "ENT Specialist",
        "experience": "15 years",
        "rating": "4.7",
        "location_url": "https://maps.google.com/?q=E-33+Sector+25+Noida",
        "website_url": "https://www.drmeerapatel-ent.com",
    },
    {
        "name": "Dr. Arjun Reddy",
        "contact": "+91-98765-43220",
        "address": "B-11, Sector 40, Noida, UP - 201301",
        "qualification": "MBBS, MD Gastroenterology",
        "specialization": "Gastroenterologist",
        "experience": "17 years",
        "rating": "4.8",
        "location_url": "https://maps.google.com/?q=B-11+Sector+40+Noida",
        "website_url": "https://www.drarjunreddy-gastro.com",
    },
    {
        "name": "Dr. Pooja Khanna",
        "contact": "+91-98765-43221",
        "address": "C-22, Sector 8, Noida, UP - 201301",
        "qualification": "MBBS, MD Endocrinology",
        "specialization": "Endocrinologist",
        "experience": "12 years",
        "rating": "4.6",
        "location_url": "https://maps.google.com/?q=C-22+Sector+8+Noida",
        "website_url": "https://www.drpoojakhanna-endo.com",
    },
    {
        "name": "Dr. Rohit Choudhary",
        "contact": "+91-98765-43222",
        "address": "D-8, Sector 22, Noida, UP - 201301",
        "qualification": "MBBS, MS Urology",
        "specialization": "Urologist",
        "experience": "14 years",
        "rating": "4.7",
        "location_url": "https://maps.google.com/?q=D-8+Sector+22+Noida",
        "website_url": "https://www.drrohitchoudhary-uro.com",
    },
    {
        "name": "Dr. Sneha Kapoor",
        "contact": "+91-98765-43223",
        "address": "G-14, Sector 31, Noida, UP - 201301",
        "qualification": "MBBS, MD Rheumatology",
        "specialization": "Rheumatologist",
        "experience": "13 years",
        "rating": "4.5",
        "location_url": "https://maps.google.com/?q=G-14+Sector+31+Noida",
        "website_url": "https://www.drsnehakapoor-rheuma.com",
    },
]


def get_hospitals_data() -> List[Dict[str, str]]:
    return list(HOSPITALS_DATA)


def get_doctors_data() -> List[Dict[str, str]]:
    return list(DOCTORS_DATA)


def get_consultant_directory() -> Dict[str, List[Dict[str, str]]]:
    return {"hospitals": get_hospitals_data(), "doctors": get_doctors_data()}


def search_providers(query: str) -> Dict[str, List[Dict[str, str]]]:
    query_lower = query.lower()
    hospitals = [hospital for hospital in HOSPITALS_DATA if query_lower in hospital["name"].lower()]
    doctors = [doctor for doctor in DOCTORS_DATA if query_lower in doctor["name"].lower()]
    return {"hospitals": hospitals, "doctors": doctors}


__all__ = ["get_hospitals_data", "get_doctors_data", "get_consultant_directory", "search_providers"]
